# Generated by Django 5.2.2 on 2025-06-08 11:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindermodel',
            name='id',
            field=models.CharField(default=uuid.UUID('be330328-11a0-4d74-9d1a-71a756148c36'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='remindermodel',
            name='isremind',
            field=models.BooleanField(default=False),
        ),
    ]
